#!/bin/bash
# Author: Sebastian Opiyo
# Date: May 28, 2020
# Modified: May 28, 2020
# Descr: Format the output of some of the admim commands.

echo Start of the script
echo 
date | awk '{print $1}'
echo 
uptime | awk '{print $3}'
echo
df -h | grep revgeek

echo End of script!!!
