#!/bin/bash
# Author: Sebastian Opiyo
# Date: May 28, 2020
# Modified: May 28, 2020
# Descr: The script will ping remote hosts, all at once.

hosts="/media/revgeek/Data/hackwaks/all-bashing/bash-scripting/ps/hosts-ip"

echo Let us ping the host to find out their availability.
echo

for host in $(cat $hosts)
do
	ping -c1 $host &> /dev/null
	if [ $? -eq 0 ]
	then
	echo $host is OK
	else
	echo $host is NOT OK
	fi
done
echo 
echo End of the ping results!!!
