#!/bin/bash

# Author: Sebastian Opiyo
# Description: The script is meant reset display resolution.
# Date Created: Sep 18, 2020
# Date Modified: Sep 18, 2020

# Command Vars
check=xrandr
newname=sudo xrandr --newmode "1280x1024_60.00"  109.00  1280 1368 1496 1712  1024 1027 1034 1063 -hsync +vsync
setmode=sudo xrandr --output VGA-1 --mode 1280x1024_60.00


echo Set Resolution by "1280x1024"
echo
$chech
echo
$newname
echo
$setmode
echo --------------Seba is the Big Deal!----------------
echo Done!
